version: '3.9'

services:
  frontend:
    build: 
      context: ../../../blockscout-frontend
      dockerfile: Dockerfile
    # pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend-manual'
    env_file:
      -  ../envs/common-frontend.env
    ports:
      - "127.0.0.1:3000:3000"
